[[constraint]]
  branch = "master"
  name = "github.com/appscode/go-hetzner"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.4.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[override]]
  branch = "release-1.11"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.11"
  name = "k8s.io/apimachinery"

[[override]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "6.0.0-beta"

[prune]
  go-tests = true
  unused-packages = true
