[[constraint]]
  branch = "master"
  name = "github.com/appscode/go-hetzner"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.6.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/miekg/dns"
  revision = "5364553f1ee9cddc7ac8b62dce148309c386695b"

[[override]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  branch = "release-1.11"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
